import oracledb
def get_connection():
    return oracledb.connect(
        user="SYS",
        password="123456789",
        dsn="dsn",
        mode=oracledb.SYSDBA
    )

def create_tables():
    conn=get_connection()
    cursor=conn.cursor()
    cursor.execute("""
    BEGIN
        EXECUTE IMMEDIATE ' CREATE TABLE users (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            username VARCHAR2(50) UNIQUE,
            password VARCHAR2(50),
            PRIMARY KEY(id)
        )';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != -955 THEN
                RAISE;
            END IF;
    END;
    """)

    cursor.execute("""
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE user_courses(
            user_id NUMBER,
            course_id NUMBER,
            PRIMARY KEY (user_id, course_id)
        )';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE != =955 THEN
                 RAISE;
            END IF;
    END;
    """)

    conn.commit()
    cursor.close()
    conn.close()